import { type Box, BoxTypes } from './types';

export const boxes: Box[] = [
  { id: 0, name: 'Start', type: BoxTypes.Start, pids: [] },
  { id: 7, name: 'Schloss Sturmschleier', type: BoxTypes.Position, pids: [{ id: 1, type: 0 }] },
  { id: 1, name: 'Margit, das Grausame Mal', type: BoxTypes.Boss, pids: [{ id: 56, type: 0 }] },
  { id: 2, name: 'Godrick der Verpflanzte', type: BoxTypes.Boss, pids: [{ id: 7, type: 0 }] },
  {
    id: 3,
    name: 'Liurnia-Seenland',
    type: BoxTypes.Position,
    pids: [
      { id: 2, type: 0 },
      { id: 56, type: 0 },
    ],
  },
  { id: 4, name: 'Rennala, Königin des Vollmonds', type: BoxTypes.Boss, pids: [{ id: 13, type: 0 }] },
  { id: 8, name: 'Königliche Hauptstadt', type: BoxTypes.Position, pids: [{ id: 48, type: 0 }] },
  { id: 5, name: 'Godfrey, Erster Eldenfürst', type: BoxTypes.Boss, pids: [{ id: 8, type: 0 }] },
  { id: 9, name: 'Ranni', type: BoxTypes.NPC, pids: [{ id: 75, type: 0 }] },
  { id: 10, name: 'Löwenartiger Bastard', type: BoxTypes.Boss, pids: [{ id: 59, type: 0 }] },
  {
    id: 11,
    name: 'Radahn',
    type: BoxTypes.Boss,
    pids: [
      { id: 58, type: 0 },
      { id: 12, type: 0 },
    ],
  },
  { id: 12, name: 'Alexander', type: BoxTypes.NPC, pids: [{ id: 56, type: 0 }] },
  { id: 13, name: 'Roter Wolf', type: BoxTypes.Boss, pids: [{ id: 3, type: 0 }] },
  { id: 14, name: 'Morgott, König des Mals', type: BoxTypes.Boss, pids: [{ id: 5, type: 0 }] },
  { id: 15, name: 'Mimische Träne', type: BoxTypes.Boss, pids: [{ id: 54, type: 0 }] },
  { id: 16, name: 'Tapfere Gargoyles', type: BoxTypes.Boss, pids: [{ id: 15, type: 0 }] },
  {
    id: 17,
    name: 'Fortissax, der Lichdrache',
    type: BoxTypes.Boss,
    pids: [
      { id: 18, type: 0 },
      { id: 63, type: 0 },
    ],
  },
  { id: 18, name: 'Fia', type: BoxTypes.NPC, pids: [{ id: 60, type: 0 }] },
  { id: 19, name: 'Zu den Berggipfeln der Riesen', type: BoxTypes.Position, pids: [{ id: 14, type: 0 }] },
  { id: 20, name: 'Feuerriese', type: BoxTypes.Boss, pids: [{ id: 19, type: 0 }] },
  { id: 21, name: 'Baum in Brand setzen', type: BoxTypes.Action, pids: [{ id: 20, type: 0 }] },
  { id: 22, name: 'Nach Farum Azula', type: BoxTypes.Position, pids: [{ id: 21, type: 0 }] },
  { id: 23, name: '„Schwarze Klinge“ Maliketh', type: BoxTypes.Boss, pids: [{ id: 79, type: 0 }] },
  { id: 24, name: '„Drachenfürst“ Placidusax', type: BoxTypes.Boss, pids: [{ id: 79, type: 0 }] },
  { id: 25, name: 'Zur Aschenen Hauptstadt', type: BoxTypes.Position, pids: [{ id: 23, type: 0 }] },
  { id: 26, name: 'Sir Gideon Ofnir', type: BoxTypes.Boss, pids: [{ id: 25, type: 0 }] },
  { id: 27, name: 'Godfrey / Hoarah Loux', type: BoxTypes.Boss, pids: [{ id: 26, type: 0 }] },
  { id: 28, name: 'Eldenbestie', type: BoxTypes.Boss, pids: [{ id: 27, type: 0 }] },
  { id: 29, name: 'Zeitalter des Zerfalls', type: BoxTypes.End, pids: [{ id: 35, type: 0 }] },
  {
    id: 30,
    name: 'Zeitalter der Nachtgeborenen',
    type: BoxTypes.End,
    pids: [
      { id: 39, type: 0 },
      { id: 35, type: 0 },
    ],
  },
  {
    id: 31,
    name: 'Zeitalter der Verzweiflung',
    type: BoxTypes.End,
    pids: [
      { id: 40, type: 0 },
      { id: 35, type: 0 },
    ],
  },
  {
    id: 32,
    name: 'Zeitalter der Ordnung',
    type: BoxTypes.End,
    pids: [
      { id: 41, type: 0 },
      { id: 35, type: 0 },
    ],
  },
  {
    id: 33,
    name: 'Zeitalter der Sterne',
    type: BoxTypes.End,
    pids: [{ id: 36, type: 0 }],
  },
  {
    id: 34,
    name: 'Herr der Rasenden Flamme',
    type: BoxTypes.End,
    pids: [
      { id: 37, type: 0 },
      { id: 35, type: 0 },
    ],
  },
  { id: 35, name: 'Marika berühren', type: BoxTypes.Action, pids: [{ id: 28, type: 0 },{ id: 80, type: 0 }] },
  {
    id: 36,
    name: 'Rannis Rufzeichen berühren',
    type: BoxTypes.Action,
    pids: [
      { id: 67, type: 0 },
      { id: 28, type: 0 },
    ],
  },
  {
    id: 37,
    name: 'Rasende Flamme empfangen',
    type: BoxTypes.Action,
    pids: [
      { id: 38, type: 0 },
      { id: 78, type: 0 },
    ],
  },
  { id: 38, name: 'Hyetta, Fingerjungfer der Drei Finger', type: BoxTypes.NPC, pids: [{ id: 3, type: 0 }] },
  { id: 39, name: 'Heilrune des Todesprinzen', type: BoxTypes.NPC, pids: [{ id: 17, type: 0 }] },
  { id: 40, name: 'Dungfresser', type: BoxTypes.NPC, pids: [{ id: 77, type: 0 }] },
  { id: 41, name: 'Goldmaske', type: BoxTypes.NPC, pids: [{ id: 8, type: 0 }] },
  { id: 42, name: 'Geweihtes Schneefeld', type: BoxTypes.Position, pids: [{ id: 14, type: 0 }] },
  { id: 43, name: 'Ordina, Liturgische Stadt', type: BoxTypes.Position, pids: [{ id: 42, type: 0 }] },
  { id: 44, name: 'Haligbaum', type: BoxTypes.Position, pids: [{ id: 43, type: 0 }] },
  { id: 45, name: '„Haligbaumritterin“ Loretta', type: BoxTypes.Boss, pids: [{ id: 44, type: 0 }] },
  { id: 46, name: 'Malenia', type: BoxTypes.Boss, pids: [{ id: 45, type: 0 }] },
  { id: 47, name: 'Kommandant Niall', type: BoxTypes.Boss, pids: [{ id: 19, type: 0 }] },
  { id: 48, name: 'Altus-Plateau', type: BoxTypes.Position, pids: [{ id: 4, type: 0 }] },
  { id: 49, name: 'Schattenburg', type: BoxTypes.Position, pids: [{ id: 48, type: 0 }] },
  { id: 50, name: 'Haus Vulkan', type: BoxTypes.Position, pids: [{ id: 48, type: 0 }] },
  { id: 51, name: 'Adliger der Götterskalpe', type: BoxTypes.Boss, pids: [{ id: 50, type: 0 }] },
  { id: 52, name: 'Rykard', type: BoxTypes.Boss, pids: [{ id: 51, type: 0 }] },
  { id: 53, name: '„Dornen-Elemer“', type: BoxTypes.Boss, pids: [{ id: 49, type: 0 }] },
  {
    id: 54,
    name: 'Nokron, Ewige Stadt',
    type: BoxTypes.Position,
    pids: [
      { id: 57, type: 0 },
      { id: 11, type: 0 },
    ],
  },
  {
    id: 55,
    name: 'Siofra',
    type: BoxTypes.Position,
    pids: [
      { id: 57, type: 0 },
      { id: 54, type: 0 },
    ],
  },
  { id: 56, name: 'Limgrave', type: BoxTypes.Position, pids: [{ id: 0, type: 0 }] },
  { id: 57, name: 'Nebelwald', type: BoxTypes.Position, pids: [{ id: 56, type: 0 }] },
  { id: 58, name: 'Caelid', type: BoxTypes.Position, pids: [{ id: 0, type: 0 }] },
  { id: 59, name: 'Halbinsel der Tränen', type: BoxTypes.Position, pids: [{ id: 56, type: 0 }] },
  { id: 60, name: 'Tafelrundfeste', type: BoxTypes.Position, pids: [{ id: 0, type: 0 }] },
  { id: 61, name: 'Ahnengeist', type: BoxTypes.Boss, pids: [{ id: 55, type: 0 }] },
  { id: 62, name: 'Königlicher Ahnengeist', type: BoxTypes.Boss, pids: [{ id: 15, type: 0 }] },
  {
    id: 63,
    name: 'Tiefwurzel-Tiefen',
    type: BoxTypes.Position,
    pids: [
      { id: 78, type: 0 },
      { id: 16, type: 0 },
    ],
  },
  {
    id: 64,
    name: 'Ainsel (unterer Lauf)',
    type: BoxTypes.Position,
    pids: [
      { id: 3, type: 0 },
      { id: 66, type: 0 },
    ],
  },
  {
    id: 66,
    name: 'Ainsel (oberer Lauf)',
    type: BoxTypes.Position,
    pids: [
      { id: 9, type: 0 },
      { id: 63, type: 0 },
    ],
  },
  { id: 65, name: 'Fäulnissee', type: BoxTypes.Position, pids: [{ id: 66, type: 0 }] },
  {
    id: 67,
    name: 'Ranni heiraten',
    type: BoxTypes.Action,
    pids: [{ id: 70, type: 0 }],
  },
  { id: 68, name: 'Drachenblutsoldat von Nokstella', type: BoxTypes.Boss, pids: [{ id: 64, type: 0 }] },
  { id: 69, name: 'Astel, Ausgeburt der Finsternis', type: BoxTypes.Boss, pids: [{ id: 65, type: 0 }] },
  { id: 70, name: 'Mondlichtaltar', type: BoxTypes.Position, pids: [{ id: 69, type: 0 }] },
  { id: 71, name: 'Dynastie Mohgwyn', type: BoxTypes.Position, pids: [{ id: 42, type: 0 }] },
  { id: 72, name: '„Blutfürst“ Mohg', type: BoxTypes.Boss, pids: [{ id: 71, type: 0 }] },
  { id: 73, name: 'Haus Caria', type: BoxTypes.Position, pids: [{ id: 3, type: 0 }] },
  { id: 74, name: 'Königliche Ritterin Loretta', type: BoxTypes.Boss, pids: [{ id: 73, type: 0 }] },
  { id: 75, name: 'Drei Schwestern', type: BoxTypes.Position, pids: [{ id: 74, type: 0 }] },
  { id: 76, name: 'Mohg, das Mal', type: BoxTypes.Boss, pids: [{ id: 77, type: 0 }] },
  { id: 77, name: 'Kanalisation der Hauptstadt', type: BoxTypes.Position, pids: [{ id: 8, type: 0 }] },
  { id: 78, name: 'Siegel der Rasenden Flamme', type: BoxTypes.Position, pids: [{ id: 76, type: 0 }] },
  { id: 79, name: 'Duo der Götterskalpe', type: BoxTypes.Boss, pids: [{ id: 22, type: 0 }] },
  {
    id: 80,
    name: 'Rasende Flamme reinigen',
    type: BoxTypes.Action,
    pids: [
      { id: 24, type: 0 },
      { id: 81, type: 0 },
      { id: 37, type: 0 },
    ],
  },
  { id: 81, name: 'Goldene Nadel erhalten', type: BoxTypes.Action, pids: [{ id: 46, type: 0 }] },
];
